# Generated by Django 4.1 on 2022-08-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faucet.address'),
            preserve_default=False,
        ),
    ]
